[package]
name = "steam_price_tracker"
version = "0.1.0"
authors = ["Murtaza <murtaza.munshi@ekomercio.com.mx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
